auto: true

markdown: rdiscount
pygments: true
paginate: 8
paginate_path: "page:num"
permalink: /:title

title: mingzhang.com
url: http://mingzhang0309.github.com
feed: /atom.xml
author_info: <a href="http://mingzhang0309.github.com">张明</a>
